POST http://localhost:3333/videos
Content-Type: application/json

{
    "title": "Video ",
    "description": "Esse é o quarto video",
    "duration": 180
}

###

GET  http://localhost:3333/videos?searche=node

###

PUT http://localhost:3333/videos/f024caec-210f-4e28-93ef-a72d27a63e02
Content-Type: application/json

{
    "title": "Video 03",
    "description": "Esse é o segundo video",
    "duration": 180
}

### 

DELETE http://localhost:3333/videos/f024caec-210f-4e28-93ef-a72d27a63e02
